"""Durable Runtime intake for todo and supervision Task executions."""

import uuid

from loguru import logger
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import Settings, get_settings
from app.dao.base import tenant_context
from app.database import async_session
from app.models.agent import Agent
from app.models.task import Task, TaskLog
from app.services.agent_runtime.adapter import RuntimeCommandIntake
from app.services.agent_runtime.config import decide_runtime_v2
from app.services.agent_runtime.contracts import RunHandle, StartRunCommand
from app.services.task_graph_service import TaskBlockedError, task_graph_service

settings = get_settings()


class TaskRuntimeIntakeError(RuntimeError):
    """A Task selected for Runtime v2 cannot be registered safely."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


def _task_goal(task: Task) -> str:
    if task.type == "supervision":
        goal = f"[督办任务] {task.title}"
    else:
        goal = f"[任务执行] {task.title}"
    if task.description:
        goal += f"\n任务描述: {task.description}"
    if task.type == "supervision":
        if task.supervision_target_name:
            goal += f"\n督办对象: {task.supervision_target_name}"
        return goal + "\n\n请执行此督办任务：联系督办对象，了解进展，并汇报结果。"
    return goal + "\n\n请认真完成此任务，给出详细的执行结果。"


async def enqueue_task_runtime(
    db: AsyncSession,
    *,
    task: Task,
    agent: Agent,
    execution_id: uuid.UUID | None = None,
    settings_override: Settings | None = None,
    attempt_id: uuid.UUID | None = None,
    actor_user_id: uuid.UUID | None = None,
) -> RunHandle | None:
    """Register one Task execution in the caller transaction when v2 is selected."""
    runtime_settings = settings_override or settings
    if task.type not in {"todo", "supervision"}:
        raise TaskRuntimeIntakeError(
            "task_type_unsupported",
            f"Runtime does not support Task type {task.type!r}",
        )
    decision = decide_runtime_v2(
        agent_id=agent.id,
        source_type="task",
        settings=runtime_settings,
    )
    if not decision.use_v2:
        return None
    if task.agent_id != agent.id:
        raise TaskRuntimeIntakeError(
            "task_agent_mismatch",
            "Task does not belong to the requested Agent",
        )
    if agent.tenant_id is None:
        raise TaskRuntimeIntakeError(
            "agent_tenant_missing",
            "Runtime Task Agent has no tenant",
        )
    model_id = agent.primary_model_id
    if model_id is None:
        raise TaskRuntimeIntakeError(
            "agent_model_missing",
            "Runtime Task Agent has no configured primary model",
        )

    if task.type == "supervision":
        occurrence_id = execution_id or uuid.uuid4()
        source_execution_id = f"task:{task.id}:supervision:{occurrence_id}"
    else:
        # Phase 2E §5 R3/R5: the STABLE key ``task:{id}`` is reserved for
        # the FIRST attempt only.  An explicit human retry after a terminal
        # failed/cancelled Run registers a NEW Run under
        # ``task:{id}:retry:{attempt_id}`` (the attempt id is generated by
        # the owning service, never reused); retries never collide with the
        # stable first-attempt key and never auto-retry (R4).
        # ``attempt_id=None`` (every legacy call site) keeps the
        # byte-identical stable key.
        source_execution_id = (
            f"task:{task.id}:retry:{attempt_id}" if attempt_id is not None else f"task:{task.id}"
        )

    # Phase 2D execution gate (design §5.4): before creating a Run, refuse to
    # enqueue a dependency-blocked todo task.  A todo task whose direct
    # dependencies are not all ``done`` is BLOCKED -> raise TaskBlockedError so
    # the caller keeps it ``pending`` + logs the block and creates no Run.  A
    # ready task (no unmet deps) proceeds unchanged.  Supervision carries no
    # dependency edges, so the gate returns empty for it (no behavior change).
    # agent.tenant_id is already narrowed to non-None by the gate above.
    if task.type == "todo":
        gate_tenant: uuid.UUID = agent.tenant_id
        unmet = await task_graph_service.ensure_ready(db, task=task, tenant_id=gate_tenant)
        if unmet:
            raise TaskBlockedError(task.id, unmet)

    handle = await RuntimeCommandIntake(
        db,
        settings=runtime_settings,
    ).start_run(
        StartRunCommand(
            tenant_id=agent.tenant_id,
            agent_id=agent.id,
            source_type="task",
            source_id=str(task.id),
            source_execution_id=source_execution_id,
            goal=_task_goal(task),
            run_kind="background",
            model_id=model_id,
            delivery_status="not_required",
            idempotency_key=f"start:{source_execution_id}",
            payload={
                "task_id": str(task.id),
                "task_type": task.type,
                "title": task.title,
                "description": task.description,
                **({"task_attempt": str(attempt_id)} if attempt_id is not None else {}),
            },
            origin_user_id=task.created_by,
            # Phase 2E §10.1 (closes U6): the Execute caller is the Run's
            # actor, not the task creator.  Legacy call sites (POST auto-
            # enqueue, the trigger path) pass nothing and default to
            # task.created_by, keeping the old behavior byte-identical.
            actor_user_id=actor_user_id if actor_user_id is not None else task.created_by,
        )
    )
    task.status = "doing"
    if handle.created:
        db.add(
            TaskLog(
                task_id=task.id,
                content=f"🤖 已进入持久化执行队列（Run {handle.run_id}）",
            )
        )
    return handle


async def _try_enqueue_runtime_task(
    task_id: uuid.UUID,
    agent_id: uuid.UUID,
    *,
    execution_id: uuid.UUID,
) -> RunHandle | None:
    async with async_session() as db:
        async with db.begin():
            task_result = await db.execute(
                select(Task).where(
                    Task.id == task_id,
                    Task.agent_id == agent_id,
                )
            )
            task = task_result.scalar_one_or_none()
            if task is None:
                raise TaskRuntimeIntakeError(
                    "task_not_found",
                    "Task does not exist for the requested Agent",
                )
            agent_result = await db.execute(
                select(Agent).where(
                    Agent.id == agent_id,
                    Agent.deleted_at.is_(None),
                )
            )
            agent = agent_result.scalar_one_or_none()
            if agent is None:
                raise TaskRuntimeIntakeError(
                    "agent_not_found",
                    "Task Agent does not exist",
                )
            with tenant_context(agent.tenant_id):
                return await enqueue_task_runtime(
                    db,
                    task=task,
                    agent=agent,
                    execution_id=execution_id,
                )


async def execute_task(task_id: uuid.UUID, agent_id: uuid.UUID) -> None:
    """Register one Task execution; the Runtime worker owns all model/tool work."""
    logger.info(f"[TaskExec] Starting task {task_id} for agent {agent_id}")

    try:
        runtime_handle = await _try_enqueue_runtime_task(
            task_id,
            agent_id,
            execution_id=uuid.uuid4(),
        )
    except TaskBlockedError as blocked:
        # Dependency gate (design §5.4): the task has unmet direct
        # dependencies, so NO Run is created and it stays pending.  This is a
        # legitimate outcome (not a failure) — log the block notice, not an
        # error, and let the human resolve / re-trigger.
        await _log_blocked(task_id, blocked.reason)
        return
    except TaskRuntimeIntakeError as exc:
        if exc.code == "task_not_found":
            logger.warning(f"[TaskExec] Task {task_id} not found")
            return
        logger.error(f"[TaskExec] Runtime intake failed ({exc.code}): {exc}")
        await _log_error(task_id, f"持久化执行登记失败: {exc.code}")
        return
    except Exception as exc:
        error_code = getattr(exc, "code", type(exc).__name__)
        logger.error(f"[TaskExec] Runtime intake failed ({error_code}): {exc}")
        await _log_error(task_id, f"持久化执行登记失败: {error_code}")
        return
    if runtime_handle is not None:
        logger.info(
            f"[TaskExec] Task {task_id} queued as Runtime Run {runtime_handle.run_id}"
        )
        return
    await _log_error(
        task_id,
        "统一 Runtime 当前未对 task 入口启用；未回退旧执行循环",
    )


async def _log_error(task_id: uuid.UUID, message: str) -> None:
    """Add an error log to the task."""
    logger.error(f"[TaskExec] Error for {task_id}: {message}")
    async with async_session() as db:
        db.add(TaskLog(task_id=task_id, content=f"❌ {message}"))
        await db.commit()


async def _log_blocked(task_id: uuid.UUID, unmet: list[uuid.UUID]) -> None:
    """Record a dependency-blocked trigger (design §5.4): the task stays
    ``pending`` and NO Run is created.  The human resolves the unmet
    dependencies (or removes the edges) and re-triggers.
    """
    detail = ", ".join(str(x) for x in unmet)
    logger.info(f"[TaskExec] Task {task_id} not enqueued — blocked by unmet deps [{detail}]")
    async with async_session() as db:
        db.add(TaskLog(task_id=task_id, content=f"⛔ 依赖未满足，暂不可执行：未 done 前置 = [{detail}]"))
        await db.commit()
